<a href="https://colab.research.google.com/github/Nakib-Nasrullah/Dengue_Research/blob/main/Dengue_positive_negative.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Data handling and visualization
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Settings
import warnings
warnings.filterwarnings('ignore')
sns.set_style('whitegrid')

print("All libraries imported successfully!!")

All libraries imported successfully!!

In [2]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Datasets/Dengue_final_dataset_updated.csv')
print("Dataset loaded successfully!!")
print(f"\n Dataset shape: {df.shape}")

Mounted at /content/drive
Dataset loaded successfully!!

 Dataset shape: (23360, 23)

In [3]:
# View first 5 rows
print("First 5 Patients")
df.head()

First 5 Patients

,Date,District,Max_Temp,Min_Temp,Avg_Temp,Humidity,Rainfall,Rainfall_Lag_7,Rainfall_Lag_14,Rainfall_Lag_21,...,Temp_Lag_21,Temp_Lag_30,Humidity_Lag_7,Humidity_Lag_14,Humidity_Lag_21,Humidity_Lag_30,Dengue_Lag_7,Population_Density,Urban_Index,Dengue_case
0,1/1/2025,Dhaka,30.04,20.69,25.36,62.83,2.46,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1697.69,0.23,26
1,1/2/2025,Dhaka,34.75,28.45,31.60,64.08,4.81,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1697.69,0.23,35
2,1/3/2025,Dhaka,35.54,26.85,31.20,53.80,1.74,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1697.69,0.23,8
3,1/4/2025,Dhaka,32.20,25.53,28.87,65.11,3.22,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1697.69,0.23,28
4,1/5/2025,Dhaka,31.87,22.06,26.96,55.28,0.00,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1697.69,0.23,1

In [4]:
# Dataset information
print("Dataset information:")
df.info()

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23360 entries, 0 to 23359
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                23360 non-null  object
 1   District            23360 non-null  object
 2   Max_Temp            23360 non-null  float64
 3   Min_Temp            23360 non-null  float64
 4   Avg_Temp            23360 non-null  float64
 5   Humidity            23360 non-null  float64
 6   Rainfall            23360 non-null  float64
 7   Rainfall_Lag_7      23360 non-null  float64
 8   Rainfall_Lag_14     23360 non-null  float64
 9   Rainfall_Lag_21     23360 non-null  float64
 10  Rainfall_Lag_30     23360 non-null  float64
 11  Temp_Lag_7          23360 non-null  float64
 12  Temp_Lag_14         23360 non-null  float64
 13  Temp_Lag_21         23360 non-null  float64
 14  Temp_Lag_30         23360 non-null  float64
 15  Humidity_Lag_7      23360 non-null  float64
 16  Humidity_Lag_14     23360 non-null  float64
 17  Humidity_Lag_21     23360 non-null  float64
 18  Humidity_Lag_30     23360 non-null  float64
 19  Dengue_Lag_7        23360 non-null  int64
 20  Population_Density  23360 non-null  float64
 21  Urban_Index         23360 non-null  float64
 22  Dengue_case         23360 non-null  int64
dtypes: float64(19), int64(2), object(2)
memory usage: 4.1+ MB

In [5]:
# Statistical summary
print("Statistical Summary:")
df.describe()

Statistical Summary:

,Max_Temp,Min_Temp,Avg_Temp,Humidity,Rainfall,Rainfall_Lag_7,Rainfall_Lag_14,Rainfall_Lag_21,Rainfall_Lag_30,Temp_Lag_7,...,Temp_Lag_21,Temp_Lag_30,Humidity_Lag_7,Humidity_Lag_14,Humidity_Lag_21,Humidity_Lag_30,Dengue_Lag_7,Population_Density,Urban_Index,Dengue_case
count,23360.000000,23360.000000,23360.000000,23360.000000,23360.000000,23360.000000,23360.000000,23360.000000,23360.000000,23360.000000,...,23360.000000,23360.000000,23360.000000,23360.000000,23360.000000,23360.000000,23360.000000,23360.000000,23360.000000,23360.000000
mean,30.974776,23.470154,27.222495,70.604415,11.838815,82.535213,11.744530,11.694893,11.630840,26.699265,...,25.652726,24.978611,69.456096,68.302332,67.151801,65.678147,346.982620,1158.903438,0.542344,4.386045
std,3.458484,3.748228,3.532907,10.982238,11.008745,68.842884,11.095333,11.140083,11.197264,3.961403,...,6.383410,7.501424,13.777808,17.347328,19.674321,22.224617,162.996326,409.902771,0.208367,18.777408
min,25.000000,15.060000,20.050000,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,303.400000,0.200000,0.000000
25%,27.950000,20.480000,24.220000,61.850000,3.000000,18.460000,2.810000,2.690000,2.500000,26.240000,...,26.570000,26.620000,60.467500,61.097500,60.567500,59.910000,202.000000,861.045000,0.370000,0.000000
50%,30.980000,23.495000,27.240000,69.990000,8.365000,66.175000,8.365000,8.365000,8.365000,27.190000,...,27.150000,27.140000,71.700000,69.985000,69.980000,69.980000,314.000000,1104.420000,0.530000,0.000000
75%,33.960000,26.430000,30.190000,79.290000,17.670000,156.832500,17.670000,17.670000,17.670000,28.120000,...,27.710000,27.610000,81.240000,79.290000,79.290000,79.290000,538.000000,1448.182500,0.702500,2.000000
max,37.000000,31.900000,34.450000,90.000000,40.000000,248.260000,40.000000,40.000000,40.000000,31.770000,...,30.140000,29.540000,88.060000,90.000000,90.000000,90.000000,662.000000,1893.500000,0.900000,448.000000

In [6]:
print("Statistical Summary:")
df.describe().T

Statistical Summary:

,count,mean,std,min,25%,50%,75%,max
Max_Temp,23360.0,30.974776,3.458484,25.00,27.9500,30.980,33.9600,37.00
Min_Temp,23360.0,23.470154,3.748228,15.06,20.4800,23.495,26.4300,31.90
Avg_Temp,23360.0,27.222495,3.532907,20.05,24.2200,27.240,30.1900,34.45
Humidity,23360.0,70.604415,10.982238,50.00,61.8500,69.990,79.2900,90.00
Rainfall,23360.0,11.838815,11.008745,0.00,3.0000,8.365,17.6700,40.00
Rainfall_Lag_7,23360.0,82.535213,68.842884,0.00,18.4600,66.175,156.8325,248.26
Rainfall_Lag_14,23360.0,11.744530,11.095333,0.00,2.8100,8.365,17.6700,40.00
Rainfall_Lag_21,23360.0,11.694893,11.140083,0.00,2.6900,8.365,17.6700,40.00
Rainfall_Lag_30,23360.0,11.630840,11.197264,0.00,2.5000,8.365,17.6700,40.00
Temp_Lag_7,23360.0,26.699265,3.961403,0.00,26.2400,27.190,28.1200,31.77
Temp_Lag_14,23360.0,26.176912,5.310921,0.00,26.4775,27.170,27.8500,30.68
Temp_Lag_21,23360.0,25.652726,6.383410,0.00,26.5700,27.150,27.7100,30.14
Temp_Lag_30,23360.0,24.978611,7.501424,0.00,26.6200,27.140,27.6100,29.54
Humidity_Lag_7,23360.0,69.456096,13.777808,0.00,60.4675,71.700,81.2400,88.06
Humidity_Lag_14,23360.0,68.302332,17.347328,0.00,61.0975,69.985,79.2900,90.00
Humidity_Lag_21,23360.0,67.151801,19.674321,0.00,60.5675,69.980,79.2900,90.00
Humidity_Lag_30,23360.0,65.678147,22.224617,0.00,59.9100,69.980,79.2900,90.00
Dengue_Lag_7,23360.0,346.982620,162.996326,0.00,202.0000,314.000,538.0000,662.00
Population_Density,23360.0,1158.903438,409.902771,303.40,861.0450,1104.420,1448.1825,1893.50
Urban_Index,23360.0,0.542344,0.208367,0.20,0.3700,0.530,0.7025,0.90
Dengue_case,23360.0,4.386045,18.777408,0.00,0.0000,0.000,2.0000,448.00

In [7]:
# Convert and sort date
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date')

In [8]:
# Calculate daily change
df['Daily_Change'] = df['Dengue_case'].diff()

In [9]:
# Assign trend labels
df['Trend'] = df['Daily_Change'].apply(
    lambda x: 'Positive' if x > 0 else ('Negative' if x < 0 else 'No Change')
)

print(df[['Date','Dengue_case','Daily_Change','Trend']].head())

            Date  Dengue_case  Daily_Change      Trend
0     2025-01-01           26           NaN  No Change
22630 2025-01-01            0         -26.0   Negative
11315 2025-01-01            1           1.0   Positive
1825  2025-01-01            2           1.0   Positive
16425 2025-01-01            0          -2.0   Negative